### ISSUE TITLE
Nenhum programa disponível para instalar no Xubuntu 20.04

### ISSUE THREAD

**Issue by rauldipeas** [app-outlet/app-outlet#102]
Estou tentando rodar o App Outlet no Xubuntu 20.04, mas após instalar o programa com o pacote `.deb` e abrir através do menu, ele não exibe nenhum programa pra instalar.

![image](https://user-images.githubusercontent.com/12108031/88600059-b4078780-d043-11ea-8536-adf55016c27b.png)

**Comment by MessiasLima** [comment]
Olá Raul. Tudo bem?
A **versão atual** do App Outlet se utiliza da infraestrutura do Heroku para hospedar nosso servidor. Nos utilizamos o plano Free, por que nossos ganhos ainda não são o suficiente para custear um plano pago. 
Em consequencia disso, dependendo do uso durante o mês, a applicação pode passar um tempo indisponivel (geralmente nos ultimos dias do mês).
Quando o servidor atinge nivel de uso do plano free, ele entra em estado de hibernação.
A applicação volta a funcionar normalmente no começo do mes seguinte.

Nos ja estamos dando os primeiros passos para a o desenvolvimento de uma versão 2. Onde vamos tentar sanar esse tipo de problema.

Obrigado pelo suporte.

**Comment by rauldipeas** [comment]
Muito obrigado pelo esclarecimento! No aguardo aqui, então.
