### ISSUE TITLE
Occured an error

### ISSUE THREAD

**Issue by probonopd** [app-outlet/app-outlet#103]
App.Outlet-1.3.4.AppImage on Xubuntu 18.04

![image](https://user-images.githubusercontent.com/2480569/89054132-d81adf80-d347-11ea-8bf4-314f7575299a.png)

**Comment by MessiasLima** [comment]
Duplicated #70 #102 #101

**Comment by probonopd** [comment]
Would be good if it could say what kind of error. Did the free hosting service provider again run out of credit and one should try next month again?

**Comment by MessiasLima** [comment]
Exactly. We are working on a solution.
