### ISSUE TITLE
Categories view does not show all types of applications

### ISSUE THREAD

**Issue by N0rbert** [app-outlet/app-outlet#107]
**Describe the bug**
Categories view does not show all types of applications.

**To Reproduce**
1. Go to 'Categories'
2. Click on Audio or Video category
3. Scroll down to the end of list
4. See only FlatPak-based applications

**Expected behavior**
All application types are shown - Snap, AppImage and FlatPak. For example VLC should be shown in all three types for Audio and Video categories.

**Desktop (please complete the following information):**
 - OS: Ubuntu MATE 16.04 LTS
 - Version 1.3.4

**Comment by realgrm** [comment]
Same here. 
- Fedora and Fedora Silverblue 33
- Version 1.3.4
