### ISSUE TITLE
App outlet not loading app list ''Occured an error''

### ISSUE THREAD

**Issue by joellapointe1717** [app-outlet/app-outlet#110]
**Describe the bug**
I downloaded App outlet in Archlinux by both the Appimage and the tar.gz. They both fail to load app lists, here is the screenshot : 
[https://i.ibb.co/4MvbZ9r/Capture-d-cran-du-2020-12-27-14-12-51.png](https://i.ibb.co/4MvbZ9r/Capture-d-cran-du-2020-12-27-14-12-51.png)
Is the project dead? There is a similar problem with other appimage app managers. Most of them seems to be dead?

**To Reproduce**
1. Download appimage file
2. Flip the execution bit
3. Execute the appimage
4. Whait until the app list tries to load. See : ''Occured an error''

**Expected behavior**

**Screenshots**
[https://i.ibb.co/4MvbZ9r/Capture-d-cran-du-2020-12-27-14-12-51.png](https://i.ibb.co/4MvbZ9r/Capture-d-cran-du-2020-12-27-14-12-51.png)

**Desktop**
 - OS: [Archlinux (Reborn OS)]
 - Browser [Chromium, Firefox]
 - Version [Anyversion]

**Additional context**
It is also appening in any linux distro I have... Is the project dead

**Comment by Gideon-Felt** [comment]
I'm having the same issue, and when I visit the website to re-download the deb file I get routed to a Heroku error page:
![image](https://user-images.githubusercontent.com/58604424/103294195-9a7db980-49ae-11eb-8fcb-f70ffca34f02.png)
and all the downloads are the same, I think the entire app backend is down.

**Comment by MessiasLima** [comment]
This issue was resolved on the new version. thank for the report and sorry for the alte answer
