### ISSUE TITLE
Flatpak,AppImage,Snap Selection should be in settings instead of tabs.

### ISSUE THREAD

**Issue by nickson99** [app-outlet/app-outlet#131]
**Is your feature request related to a problem? Please describe.**
I only want flatpaks from App Outlet.Why Should i see appimages & snaps.

**Describe the solution you'd like**
Checkboxes for each in settings

**Describe alternatives you've considered**

**Additional context**
Checkboxes:- Type color fill in square (don't know the exact name and hence describing it.)

**Comment by MessiasLima** [comment]
Thank you. Your suggestion will be considered in future releases. But keep in mind that App Outlet was born to integrate the stores.

**Comment by nickson99** [comment]
Yes.
