### ISSUE TITLE
Enhancement Request: Make the package format Flatpak instead of appimage

### ISSUE THREAD

**Issue by ufkhf** [app-outlet/app-outlet#207]
I would like the app in Flatpak format. And it would be nice if you put it on 
https://flathub.org/home

**Comment by MessiasLima** [comment]
Unfortunately, it's not possible due to Flatpak Sandbox permissions. 
https://docs.flatpak.org/en/latest/sandbox-permissions.html
We don't have access to process outside the App Outlet process.
