### ISSUE TITLE
A update tab

### ISSUE THREAD

**Issue by ufkhf** [app-outlet/app-outlet#211]
**Is your feature request related to a problem? Please describe.**
Not being able to easily update the apps

**Describe the solution you'd like**
I want a update tab like KDE Discover, where i can see the updates for all package formats. Also it would be cool to make an applet that shows if there are any updates like the app MintUpdate.

https://github.com/linuxmint/mintupdate

**Describe alternatives you've considered**
None

**Additional context**
[Update tab](https://user-images.githubusercontent.com/84050866/120314586-ebca0600-c2ca-11eb-971e-6f0e2633e2cd.png)

![update app](https://user-images.githubusercontent.com/84050866/120325056-cc38da80-c2d6-11eb-8b72-f8c2297d7fda.png)

**Comment by MessiasLima** [comment]
A few things must be considered here
1. snap applications are updated automatically by the snapd
2. we cant track the version of AppImage applications
    - the user can download it in any folder he wants
    
So this will be a feature to update only the flatpaks

**Comment by ufkhf** [comment]
Yes and DEB and RPM if that gets implemented

**Comment by thorhop** [comment]
How about also having support for ostree/rpm-ostree? Just for updates ofc.
