### ISSUE TITLE
Comments and stars

### ISSUE THREAD

**Issue by ufkhf** [app-outlet/app-outlet#212]
**Is your feature request related to a problem? Please describe.**
Not being able to easy see if there are problems with a application or just to see what other people think

**Describe the solution you'd like**
I would like the ability to give stars to applications and also being able to comment on them. Being able to give stars and comments is already possible in mintInstall and KDE Discover.

**Describe alternatives you've considered**
None

**Additional context**
![stars and comments](https://user-images.githubusercontent.com/84050866/120330561-7404d700-c2dc-11eb-9ae6-c9537717513a.png)

**Comment by MessiasLima** [comment]
To do that we need a login system and a server-side application. For now, it's not possible because we don't have earnings enough to pay for the infrastructure
