### ISSUE TITLE
app outlet does not shows snap packages is it a bug or you removed snap packages 

### ISSUE THREAD

**Issue by gowdashrikanth** [app-outlet/app-outlet#224]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Evidences**
If applicable, add screenshots, videos or logs to help explain your problem.

**Environment (please complete the following information):**

-   Operating system:

-   App Outlet version:

**Additional context**

**Comment by MessiasLima** [comment]
It's necessary more information about this issue

**Comment by MessiasLima** [comment]
If you have some question, I would suggest that you use de discussion section of this repository

**Comment by MessiasLima** [comment]
If you have some question, I would suggest that you use the discussion section of this repository
