### ISSUE TITLE
App Synchronization

### ISSUE THREAD

**Issue by caikz** [app-outlet/app-outlet#235]
I'm using Elementary OS and before the application was perfectly fine before but now it just says App Outlet is synchronizing its database and nothing ever loads. Everything is just blank and unable to install and I don't know what the problem is. I would gladly appreciate some help because I love App Outlet!

**Comment by MessiasLima** [comment]
Hello @caikz . Could you please tell me which version are you using and which operating system? So I can help you

**Comment by caikz** [comment]
> Hello @caikz . Could you please tell me which version are you using and which operating system? So I can help you

elementary os 6.1 jolnir and I don't know how to view the current version of App Outlet but I downloaded it directly from this website; https://www.pling.com/p/1355468/#files-panel

**Comment by Mosaic-pixel** [comment]
Hi!
I have the same issue with same Elementary OS version. App-Outlet version i downloaded is 2.0.2.
Any ideas what could be missing? As app was working a while ago when using some Arch based distro.
Best,
Mosaic

**Comment by MessiasLima** [comment]
I have to take some time to try to fix it. While that, you can try a workaround.

1. Close the App Outlet
2. Delete the database file.(Its located on `$HOME/.config/app-outlet/database/app-outlet.db`)
3. Open the app outlet again.

Could you please try it and tell me if it works?

Thank you in advance

**Comment by Mosaic-pixel** [comment]
Hi. Nothing seems to change. Neither appimage nor .deb install does not provide different results other than empty store, even after deleting database file.
What could be wrong with elementary, because on Arch this app worked just fine..?
Best,
Mosaic

**Comment by whibs** [comment]
I know this is a "me too" comment (apologies), but I just thought I would add that I'm running Ubuntu 20.04 and I'm seeing the same behavior as @caikz describes.  I deleted the db file as suggested, with no success.

**Comment by MessiasLima** [comment]
I was investigating, Tried to run in other operating systems and it worked. 

Could you please run it using the command line and report here if there is some error message?

**Comment by whibs** [comment]
[App Outlet: terminal output](https://pastebin.com/SfsdcYkc)

**Comment by MessiasLima** [comment]
Thank you @whibs. I guess I know what is happening. I will do some testing and release an update as soon as possible
