### ISSUE TITLE
Have tired installing via appimage, .deb file and npm but all end with same result...

### ISSUE THREAD

**Issue by DividedByAll666** [app-outlet/app-outlet#255]
The app installs no issues with that being said there are no images showing up for anything minus the app-outlet logo. I also tried on a Linux Mint Install but also had the same issue. Am I missing something? Is anyone else having this issue at all?

**Comment by MessiasLima** [comment]
The images from apps are provided by the app sources (snap store, Flathub and AppImageHub). We don't have any influence on this.
