### ISSUE TITLE
NOT working on Kubuntu 22.04

### ISSUE THREAD

**Issue by pigeonskiller** [app-outlet/app-outlet#260]
Hi, sorry to inform you it does NOT work Kubuntu 22.04.

Same behavior both with double click and from terminal.

Here the log from terminal:

./App.Outlet-2.1.0.AppImage
(node:9755) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
query: PRAGMA foreign_keys = OFF
query: BEGIN TRANSACTION
query: SELECT null as database, null as schema, * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('application')
query: SELECT null as database, null as schema, * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('settings')
query: SELECT null as database, null as schema, * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('application')
query: SELECT null as database, null as schema, * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('settings')
query: PRAGMA table_info("application")
query: PRAGMA index_list("application")
query: PRAGMA foreign_key_list("application")
query: PRAGMA table_info("settings")
query: PRAGMA index_list("settings")
query: PRAGMA foreign_key_list("settings")
query: PRAGMA index_info("sqlite_autoindex_settings_1")
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'typeorm_metadata'
query: COMMIT
query: PRAGMA foreign_keys = ON
query: SELECT "Settings"."id" AS "Settings_id", "Settings"."key" AS "Settings_key", "Settings"."value" AS "Settings_value" FROM "settings" "Settings" WHERE "Settings"."key" = ? LIMIT 1 -- PARAMETERS: ["LAST_SYNC"]
No need to synchronize
[9755:0523/155641.928359:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
Trace/breakpoint trap (core dumped)

Hope you solve the bug soon. Thanks for the app.

**Comment by BenHerbst** [comment]
Same issue on Pop!_OS 22.04. Using NVIDIA propriety drivers
