### ISSUE TITLE
Crie um  padrão de arquivos de tradução

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [app-outlet/app-outlet#27]
[A forma como você está colocando os arquivos de tradução não cobrem todo o programa](https://github.com/app-outlet/app-outlet/blob/master/src/assets/i18n/en.json) o que impede a criação de uma ferramenta que automatize e/ou facilite a criação, além de que elas não estão sendo carregadas

**Comment by MessiasLima** [comment]
Recomenda alguma ferramenta? Eu so conheço o transifex, mas esse é pago

**Comment by MessiasLima** [comment]
related issue: https://github.com/app-outlet/app-outlet/issues/24
