### ISSUE TITLE
[BUG] [FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.

### ISSUE THREAD

**Issue by RafaelLinux** [app-outlet/app-outlet#274]
**Describe the bug**
When I try to launch app-outlet, it crashed with a lot of HTML text ending with 
`[24151:0623/121840.724622:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.`

**To Reproduce**

1. ./App.Outlet-2.1.0.AppImage)
2. See error

**Expected behavior**
To launch App.Outlet

**Evidences**
` 
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
(node:24151) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
query: PRAGMA foreign_keys = OFF
query: BEGIN TRANSACTION
query: SELECT null as database, null as schema, * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('application')
query: SELECT null as database, null as schema, * FROM "sqlite_master" WHERE "type" = 'table' AND "name" IN ('settings')
query: SELECT null as database, null as schema, * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('application')
query: SELECT null as database, null as schema, * FROM "sqlite_master" WHERE "type" = 'index' AND "tbl_name" IN ('settings')
query: PRAGMA table_info("application")
query: PRAGMA index_list("application")
query: PRAGMA foreign_key_list("application")
query: PRAGMA table_info("settings")
query: PRAGMA index_list("settings")
query: PRAGMA foreign_key_list("settings")
query: PRAGMA index_info("sqlite_autoindex_settings_1")
query: SELECT * FROM "sqlite_master" WHERE "type" = 'table' AND "name" = 'typeorm_metadata'
query: COMMIT
query: PRAGMA foreign_keys = ON
query: SELECT "Settings"."id" AS "Settings_id", "Settings"."key" AS "Settings_key", "Settings"."value" AS "Settings_value" FROM "settings" "Settings" WHERE "Settings"."key" = ? LIMIT 1 -- PARAMETERS: ["LAST_SYNC"]
Starting synchronization
Error: Request failed with status code 502
    at createError (/tmp/.mount_App.Ouu2viah/resources/app.asar/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/tmp/.mount_App.Ouu2viah/resources/app.asar/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/tmp/.mount_App.Ouu2viah/resources/app.asar/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: httpAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'User-Agent': 'axios/0.24.0',
      host: 'appimage.github.io'
    },
    method: 'get',
    url: 'https://appimage.github.io/feed.json',
    data: undefined
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      connect: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: false,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: 0,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(asyncId)]: 60,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    connection: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _readableState: [ReadableState],
      readable: true,
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(asyncId)]: 60,
      [Symbol(kHandle)]: [TCP],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'GET https://appimage.github.io/feed.json HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'User-Agent: axios/0.24.0\r\n' +
      'host: appimage.github.io\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    insecureHTTPParser: undefined,
    path: 'https://appimage.github.io/feed.json',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 502,
      statusMessage: 'Bad Gateway',
      client: [Socket],
      _consuming: true,
      _dumped: false,
      req: [Circular],
      responseUrl: 'http://10.162.0.10:3128/https://appimage.github.io/feed.json',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 0,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'http://10.162.0.10:3128/https://appimage.github.io/feed.json',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'user-agent': [Array],
      host: [Array]
    }
  },
  response: {
    status: 502,
    statusText: 'Bad Gateway',
    headers: {
      server: 'squid/4.13',
      'mime-version': '1.0',
      date: 'Thu, 23 Jun 2022 10:18:40 GMT',
      'content-type': 'text/html;charset=utf-8',
      'content-length': '3636',
      'x-squid-error': 'ERR_READ_ERROR 0',
      vary: 'Accept-Language',
      'content-language': 'en',
      'x-cache': 'MISS from kraken',
      'x-cache-lookup': 'MISS from kraken:3128',
      via: '1.1 kraken (squid/4.13)',
      connection: 'close'
    },
    config: {
      transitional: [Object],
      adapter: [Function: httpAdapter],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus],
      headers: [Object],
      method: 'get',
      url: 'https://appimage.github.io/feed.json',
      data: undefined
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [Socket],
      connection: [Socket],
      _header: 'GET https://appimage.github.io/feed.json HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'User-Agent: axios/0.24.0\r\n' +
        'host: appimage.github.io\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      insecureHTTPParser: undefined,
      path: 'https://appimage.github.io/feed.json',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">\n' +
      '<html><head>\n' +
      '<meta type="copyright" content="Copyright (C) 1996-2020 The Squid Software Foundation and contributors">\n' +
      '<meta http-equiv="Content-Type" content="text/html; charset=utf-8">\n' +
      '<title>ERROR: The requested URL could not be retrieved</title>\n' +
      '<style type="text/css"></style>\n' +
      '</head><body id=ERR_READ_ERROR>\n' +
      '<div id="titles">\n' +
      '<h1>ERROR</h1>\n' +
      '<h2>The requested URL could not be retrieved</h2>\n' +
      '</div>\n' +
      '<hr>\n' +
      '\n' +
      '<div id="content">\n' +
      '<p>The following error was encountered while trying to retrieve the URL: <a href="https://appimage.github.io/feed.json">https://appimage.github.io/feed.json</a></p>\n' +
      '\n' +
      '<blockquote id="error">\n' +
      '<p><b>Read Error</b></p>\n' +
      '</blockquote>\n' +
      '\n' +
      '<p id="sysmsg">The system returned: <i>[No Error]</i></p>\n' +
      '\n' +
      '<p>An error condition occurred while reading data from the network. Please retry your request.</p>\n' +
      '\n' +
      '<p>Your cache administrator is <a href="mailto:webmaster?subject=CacheErrorInfo%20-%20ERR_READ_ERROR&amp;body=CacheHost%3A%20kraken%0D%0AErrPage%3A%20ERR_READ_ERROR%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Thu,%2023%20Jun%202022%2010%3A18%3A40%20GMT%0D%0A%0D%0AClientIP%3A%2010.162.7.246%0D%0AServerIP%3A%20appimage.github.io%0D%0A%0D%0AHTTP%20Request%3A%0D%0AGET%20%2Ffeed.json%20HTTP%2F1.1%0AAccept%3A%20application%2Fjson,%20text%2Fplain,%20*%2F*%0D%0AUser-Agent%3A%20axios%2F0.24.0%0D%0AConnection%3A%20close%0D%0AX-Forwarded-For%3A%2010.162.20.20%0D%0AHost%3A%20appimage.github.io%0D%0A%0D%0A%0D%0A">webmaster</a>.</p>\n' +
      '<br>\n' +
      '</div>\n' +
      '\n' +
      '<hr>\n' +
      '<div id="footer">\n' +
      '<p>Generated Thu, 23 Jun 2022 10:18:40 GMT by kraken (squid/4.13)</p>\n' +
      '\n' +
      '</div>\n' +
      '</body></html>\n'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
[24151:0623/121840.724622:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.`

**Environment:**
Operating System: openSUSE Tumbleweed 20220602
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.94.0
Qt Version: 5.15.2
Kernel Version: 5.18.1-1-default (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i7-9700K CPU @ 3.60GHz
Memory: 15.5 GiB of RAM
Graphics Processor: llvmpipe
- App Outlet version: 2.1.0
- App Outlet AppImage

**Additional context**

**Comment by MessiasLima** [comment]
duplicate #264

**Comment by MessiasLima** [comment]
It is an electron issue. I will update it for the next release.

**Comment by RafaelLinux** [comment]
ok, thanks
