### ISSUE TITLE
Link direto para o AppImage

### ISSUE THREAD

**Issue by sudo-give-me-coffee** [app-outlet/app-outlet#28]
Crie uma release Tags "Continuous" e faça upload por lá isso vai permitir que seja criado links de download direto para o AppImage

**Comment by MessiasLima** [comment]
gostaria de mais informações. tem algum exemplo ou alguma documentação em algum lugar? achei  a sugestão interessante

**Comment by sudo-give-me-coffee** [comment]
Use o apptool pra fazer upload, ele cria uma tag continua e joga ele lá, referencia:

https://github.com/sudo-give-me-coffee/PhotoGIMP/blob/74b1a2aac73bd8f614ae86c5c33ba2f48ebce570/.travis.yml#L11

**Comment by MessiasLima** [comment]
Eu dei uma olhada. Gostei da solução, mas acho que com apenas uma tag perde-se a rastreabilidade da versão. Eu então fiz isso utilizando a api REST do github. 
Obrigado pela ajuda o/ todas são muito bem vindas
