### ISSUE TITLE
Snap version not starting

### ISSUE THREAD

**Issue by MessiasLima** [app-outlet/app-outlet#41]

**Comment by HenriqueAD7** [comment]
O aplicativo em Snap é instalado normalmente, seja via cli ou interface. Contudo, ao executar o mesmo, o software não inicia. Nenhuma mensagem de erro é indicada, tanto na versão stable ou edge. Isso no Ubuntu 18.04 LTS.

A versão em AppImage funcionou normalmente.

**Comment by MessiasLima** [comment]
We requested to snapcrafters staff permission to use classic confinement. The request was denied. So we're unable to install apps using snap version. 
____

Nós solicitamos permissão ao pessoal do snapcrafters para usar classic confinement. A permissao foi negada. Entao o nosso pacote snap está impossibilitado de instalar outros pacotes.

https://forum.snapcraft.io/t/classic-confinement-for-app-outlet/13495
