### ISSUE TITLE
"Popular apps" seems misleading

### ISSUE THREAD

**Issue by popey** [app-outlet/app-outlet#42]
As I write this, the "Popular apps" category contains the following applications.

![Screenshot from 2019-10-04 17-26-21](https://user-images.githubusercontent.com/1841272/66223774-347f8500-e6cc-11e9-83e3-ec5558a5997b.png)

The flatpaks with their respective rough user-bases, based on publicly available data on flathub.

 * Ciano (~500)
 * Foliate (~600)
 * Kdenlive (~6000)
 * Nextcloud Client (~3000)
 * Thunderbird (~800)
 * Kodi (~1500)

The following AppImages, for which I have no data. Is there hard data about how "Popular" particular AppImages are, which might justify them being in this category? (a question for @probonopd probably).

 * Delir
 * Etcher

And finally these snaps, which as far as I know, haven't published install data. Other snaps likely have significantly more device installs than these though. But again, not all developers publish their data.

 * instagramport
 * tor-mkg20001

I don't know how the "Popular apps" section is populated in the application, but the applications look hand-picked, not data-based?

If they're based on data, where does that data come from? If they're hand-picked, perhaps the category should be renamed? Because "Popular" doesn't seem accurate.

**Comment by probonopd** [comment]
Due to the de-central nature of AppImage, I have no information on which ones are how popular. For example, only Ultimaker knows how often the Cura AppImage was downloaded from their website. This is by design.

**Comment by MessiasLima** [comment]
The order of the apps in "Popular" section is based in how many times the details of the app is saw in App Outlet.

It's more like a view count.

By the way, I just discovered an bug in this point.
