### ISSUE TITLE
Zoom or resize the results area.

### ISSUE THREAD

**Issue by ianp5a** [app-outlet/app-outlet#47]
I can only see 8 apps at a time on the right side.(1080 screen) This needs more scrolling and has less overview. The app icons are giant too. Way larger than app icons say in the Desktop App launcher. So they could go smaller.

Request: Zoom the results area only, with either Ctrl-Mousewheel or Ctrl +/-, or an option in settings for larger/medium/small display. Or by a slider UI element.

Benefit: If its possible to zoom out, you could spot what you are looking for quicker. Zoom back in on that, for more details or larger text. 
This can't be replaced by searching as you may not know the name of the app. Search does not work within categories either.
Benefit: Small text is harder to read for older users.

**Comment by Mikee-3000** [comment]
I use gui app managers to find new apps and being able to overview more of them at a time would be a big plus, whilst sight impaired users would benefit from being able to zoom in as @ianp5a said.

**Comment by MessiasLima** [comment]
Please take a look at the beta version. This problem was already solved on it
