### ISSUE TITLE
Actually installing apps

### ISSUE THREAD

**Issue by gardotd426** [app-outlet/app-outlet#66]
I'm on Arch and just tried using both the snap AND appimage versions of the program. I think this is an awesome idea, yet it seems that you can't actually INSTALL anything from the app? No matter what app I click on in the store, there is absolutely no option to install anything, the only options are usually to open the store page in my browser. Which would defeat the purpose, since from everything I've heard, the entire point of this app is to be a universal, distro-agnostic application search and INSTALL tool. Am I missing something, or can you not actually install anything from this app?

**Comment by MessiasLima** [comment]
The App Outlet is in active development. Que current version (v1.2.1) can only install flatpak packages. But soon in the future, we´ll release a version that can install snaps and AppImages.

For a while, only flatpaks. 

You can track the current development state here
https://github.com/app-outlet/app-outlet/issues?utf8=%E2%9C%93&q=milestone%3Av1.3+

Or using the milestone filter in issue list.

Thanks for testing AppOutlet
