### ISSUE TITLE
Request flatpak setup on Linux Mint 19.2

### ISSUE THREAD

**Issue by cosmoscalibur** [app-outlet/app-outlet#69]
According to flatpak documentation, flatpak setup is not required in Linux Mint >=18.3 but App-Outlet request me to setup flatpak to install Peek in Linux Mint 19.2.  
I installed App-Outlet (=1.1.0) using snap.

**Comment by MessiasLima** [comment]
Snap packages are not able to install packages until the snapcrafters permit us to publish apps in `--classic` confinement.

We already requested this permission and we are waiting for their verdict as you can see here.
https://forum.snapcraft.io/t/classic-confinement-for-app-outlet/13495

If they don't allow us to use this confinement, unfortunately, snap will not able to install packages.

While we wait for the response, we recommend you to use the versions available here:
https://github.com/app-outlet/app-outlet/releases/latest

Thanks for using App Outlet.
