### ISSUE TITLE
Apps not being listed

### ISSUE THREAD

**Issue by adinan-cenci** [app-outlet/app-outlet#70]
Apps are not being listed, an error message is presented: Occurred an Error Try Again.

Here is a screen shot: https://postimg.cc/mckprh6r

**Comment by avolkov-dazn** [comment]
Experiencing the same issue for the past few days.

**Comment by MessiasLima** [comment]
It is because we achieve the monthly limit of the free tier of our server host. Next month our server will be up again. 
We also will create a way to receive donations to sponsor things like this.
