### ISSUE TITLE
I can't install flatpak's

### ISSUE THREAD

**Issue by FastOSlinux** [app-outlet/app-outlet#78]
using App.Outlet-1.2.1.AppImage
Fedora silverblue 31 gnome wayland

$ ./App.Outlet-1.2.1.AppImage 
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
[18980:1107/173302.694442:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command

**Comment by sudo-give-me-coffee** [comment]
May be a Wayland hardware acceleration related issue... can you try with software rendering?

```
export LIBGL_ALWAYS_SOFTWARE=1
```

**Comment by sudo-give-me-coffee** [comment]
Your issue title does not refer to content

**Comment by wcolato** [comment]
I can't install flatpak as well.
 
![app-outlet](https://user-images.githubusercontent.com/59609098/71897198-9a98ff80-3134-11ea-9cc1-9d88343b6692.png)

**Comment by MessiasLima** [comment]
@wcolato was you using snap version?
