### ISSUE TITLE
Show version numbers in search view

### ISSUE THREAD

**Issue by theworldisnotflat** [app-outlet/app-outlet#92]
**Is your feature request related to a problem? Please describe.**
you need to click on the app to know which version it is
**Describe the solution you'd like**
If you directly see which version is in which repository this helps you choose between flatpak or else

**Describe alternatives you've considered**
alternative : use regular gnome install software which has the same default

**Comment by MessiasLima** [comment]
Show application version on search screen can introduce information that is not useful for most of the users
