### ISSUE TITLE
Search should be improved

### ISSUE THREAD

**Issue by N0rbert** [app-outlet/app-outlet#93]
Search should be improved to get more relevant search results  based not only on title, but also on description and other fields.

Steps to reproduce:

1.    Open App Outlet (1.3.2 in my case)
1.    Try to search for `markdown` or `Markdown`

Expected results:

* search results contain well known _VNote_, _Marker_, _Mark Text_, _CureMarkEd_ and may be other editors  with *markdown* in description (and of course their purpose)

Actual results:

* search results contain only three editors with *markdown* in name as shown below:

   ![app-outlet-search](https://user-images.githubusercontent.com/309456/82762049-64200080-9e07-11ea-81d6-7d6ad06c7378.png)

**Additional context**

This issue was previously discovered in similar (now obsolete) project - see https://github.com/linuxappstore/linuxappstore/issues/29

**Comment by MessiasLima** [comment]
This issue was resolved on the new version that is in beta release. Thank you for your report
