### ISSUE TITLE
App Outlet does not work on deepin 20

### ISSUE THREAD

**Issue by lxwndr** [app-outlet/app-outlet#94]
**Describe the bug**
When running the application (.AppImage and .deb) through the terminal, the following message is displayed:

> [15244:0530/224206.009199:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/App Outlet/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap

I ran the following commands to resolve the issues:

> sudo chown root '/opt/App Outlet/chrome-sandbox'
> sudo chmod 4755 '/opt/App Outlet/chrome-sandbox'

But still, an error is displayed:

![Screen Capture_deepin-terminal_20200530230636](https://user-images.githubusercontent.com/45263160/83343271-4bfc2580-a2ce-11ea-8cde-ad0f0a6a4e72.png)

**Desktop**
deepin 20 BETA (based on debian Buster)

**Additional context**
In the previous version of the system (deepin 15.11), I remember using the application without any problems.

**Comment by alexwender1** [comment]
Solution:

> sudo sysctl kernel.unprivileged_userns_clone=1

![Screen Capture_20200531003017](https://user-images.githubusercontent.com/45263160/83343835-eb70e680-a2d5-11ea-940b-eb3c88f9dc81.png)
