### ISSUE TITLE
Snap applications don't show

### ISSUE THREAD

**Issue by beepbleep** [app-outlet/app-outlet#97]
Sorry if this is a dupe of [82](https://github.com/app-outlet/app-outlet/issues/82), but it seems App Outlet isn't even trying to get a list of available snap apps. If that is the case, is it pointing to a larger problem in the future or it's just a bug to be fixed (and App Outlet is temporarily disabling the population of the Snap listing). If it's a bug, I would like to help as much as I can and do some investigation on various guest distros in a VM on my Debian. Looking forward to your answer.

**Comment by MessiasLima** [comment]
When we get a list of available apps, we do not do it separately. they are fetched all together in the same request. The filter of the type of package is made locally.
